name: brainDDgap
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pip
  - pip:
      - antspynet==0.3.1
      - antspyx==0.6.2
      - monai==1.2.0
      - nibabel
      - torch
      - -e .