name: brainDDgap
channels:
  - defaults
dependencies:
  - scikit-image=0.19.2
  - pytorch=1.12.0
  - tensorboard=2.9.1
  - nibabel=3.2.2
  - python=3.8
  - python-dateutil=2.8.2
  - pandas=1.4.3
  - pyyaml=6.0
  - tqdm=4.64
  - yacs=0.1.8
  - numpy=1.23.5
  - scipy=1.8.0
  - setuptools=59.5.0
  - pip=21.2.4
  - torchvision=0.13.0
  - h5py=3.7.0
  - pillow=9.2.0
  - scikit-learn=1.1.2
  - matplotlib=3.5.1
  - cudatoolkit=11.3
prefix: brainDDgap